---
_extends: gh-labels

repository:
  name: cdperf
  description: ':atom_symbol: ownCloud cloud performance test'
  homepage: https://owncloud.github.io/cdperf/

  private: true
  has_issues: true
  has_projects: false
  has_wiki: true
  has_downloads: false

  default_branch: main

  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  
teams:
  - name: ci
    permission: admin
  - name: employees
    permission: push

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: false
        require_code_owner_reviews: false
        dismissal_restrictions: {}
      enforce_admins: false
      restrictions:
        users: []
        teams:
          - ci
          - employees

...
