import { queryXml, store } from '@ownclouders/k6-tdk/lib/utils'
import { sleep } from 'k6'
import exec from 'k6/execution'
import { Options } from 'k6/options'

import { Client, obtainDocumentInformation } from '@/clients/onlyoffice'
import { userPool } from '@/pools'
import { clientFor } from '@/shortcuts'
import { getTestRoot } from '@/test'
import { getPoolItem } from '@/utils'
import { envValues } from '@/values'

export const options: Options = {
  vus: 1,
  iterations: 1,
  insecureSkipTLSVerify: true
}

const settings = {
  ...envValues()
}

export const open_change_save_010 = async (): Promise<void> => {
  const user = getPoolItem({ pool: userPool, n: exec.vu.idInTest })
  const userStore = store(user.userLogin)
  const ooClient = await userStore.setOrGet('root', async () => {
    const ocisClient = clientFor(user)
    const testRoot = await getTestRoot({
      client: ocisClient,
      userLogin: user.userLogin,
      platform: settings.platform.type,
      resourceName: settings.seed.container.name,
      resourceType: settings.seed.container.type,
      isOwner: false
    })

    const root = [testRoot.root, testRoot.path].filter(Boolean).join('/')
    const getResourcePropertiesResponse = await ocisClient.resource.getResourceProperties({
      root,
      resourcePath: 'sample.docx'
    })
    const [resourceId] = queryXml("$..['oc:fileid']", getResourcePropertiesResponse.body)
    const documentInformation = await obtainDocumentInformation({ client: ocisClient, resourceId })

    return new Client({
      ...documentInformation,
      // todo: make configurable
      url: `wss://onlyoffice.owncloud.test/7.3.0-184/doc/${documentInformation.documentId}/c/?EIO=4&transport=websocket`
    })
  })

  await ooClient.establishSession()
  // todo: move into pool
  const changes = '["80;AgAAADEA//8BAPOWPfV/JwAAnwAAAFIAAAAEAAAABAAAAAQAAABxAAAAcQAAAB4AAAA3AC4AMwAuADAALgAxADgANAAuAEAAQABSAGUAdgA=","58;AgAAADEAAQABAAoAAAA0AF8ANgA1ADgAAAAEAAMAAAAKAAAANABfADYANQA4AACAIAAAAAAAAAAAAA==","98;AgAAADEAAQABAAoAAAA0AF8ANgA1ADkAAAAcACcAAAAKAAAANABfADYANQA5AAoAAAA0AF8ANgA1ADcAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","34;CgAAADQAXwA2ADUAOQABABwAAQAAAAAAAAAEAAAAAwAAAA==","87;AgAAADEAAQABAAoAAAA0AF8ANgA1ADcAAAADAAoAAAA0AF8ANgA1ADcAQgAAAAAAAAAAAAAACgAAADQAXwA2ADUAOAABAAAACgAAADQAXwA2ADUAOQAB","46;CgAAADQAXwA2ADUANwAeAAMAAAAAAEIAAAAAAAAAAAAAAEIAAAAAAAAAAAAAAA==","88;AgAAADEAAQABAAoAAAA0AF8ANgA2ADAAAAAcACcAAAAKAAAANABfADYANgAwAAAAAAAAgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","46;CgAAADQAXwA2ADYAMAAdABwAAAAAAACAIAAAAAAAAAAAAACAIAAAAAAAAAAAAA==","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAAAAAABAAAAZQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAEAAAABAAAAdQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAIAAAABAAAAYwAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAMAAAABAAAAaAAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAAAQAAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAUAAAABAAAAbgAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAYAAAABAAAAZQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAcAAAABAAAAbgAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAAAgAAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAkAAAABAAAAcwAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAoAAAABAAAAYwAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAsAAAABAAAAaAAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAAwAAAABAAAA9gAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAA0AAAABAAAAbgAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAA4AAAABAAAAZQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAA8AAAABAAAAbgAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAABAAAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAABEAAAABAAAAYQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABIAAAABAAAAYgAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABMAAAABAAAAZQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABQAAAABAAAAbgAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABUAAAABAAAAZAAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABYAAAABAAAALAAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAABcAAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAABgAAAABAAAAZAAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABkAAAABAAAAYQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABoAAAABAAAAbgAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABsAAAABAAAAawAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAABwAAAABAAAAZQAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAAB0AAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAAB4AAAABAAAAZgAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAB8AAAABAAAA/AAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACAAAAABAAAAcgAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAACEAAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAACIAAAABAAAAZQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACMAAAABAAAAdQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACQAAAABAAAAcgAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACUAAAABAAAAZQAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAACYAAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAACcAAAABAAAAZwAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACgAAAABAAAAZQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACkAAAABAAAAZAAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACoAAAABAAAAdQAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACsAAAABAAAAbAAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAACwAAAABAAAAZAAAAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAAC0AAAABAAAAIQAAAAADAAAA","38;CgAAADQAXwA2ADYAMAABABwAAQAAAC4AAAACAAAAIAAAAAMAAAA=","39;CgAAADQAXwA2ADYAMAABABwAAQAAAC8AAAABAAAAevMBAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAADAAAAABAAAAevMBAAADAAAA","39;CgAAADQAXwA2ADYAMAABABwAAQAAADEAAAABAAAAevMBAAADAAAA","44;CgAAADQAXwA2ADUANwABAAMAAQAAAAAAAAAKAAAANABfADYANgAwAAAAAAA=","58;AgAAADEAAQABAAoAAAA0AF8ANgA2ADIAAAAEAAMAAAAKAAAANABfADYANgAyAACAIAAAAAAAAAAAAA==","98;AgAAADEAAQABAAoAAAA0AF8ANgA2ADMAAAAcACcAAAAKAAAANABfADYANgAzAAoAAAA0AF8ANgA2ADEAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","34;CgAAADQAXwA2ADYAMwABABwAAQAAAAAAAAAEAAAAAwAAAA==","87;AgAAADEAAQABAAoAAAA0AF8ANgA2ADEAAAADAAoAAAA0AF8ANgA2ADEAQgAAAAAAAAAAAAAACgAAADQAXwA2ADYAMgABAAAACgAAADQAXwA2ADYAMwAB","46;CgAAADQAXwA2ADYAMQAeAAMAAAAAAEIAAAAAAAAAAAAAAEIAAAAAAAAAAAAAAA==","88;AgAAADEAAQABAAoAAAA0AF8ANgA2ADQAAAAcACcAAAAKAAAANABfADYANgA0AAAAAAAAgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","46;CgAAADQAXwA2ADYANAAdABwAAAAAAACAIAAAAAAAAAAAAACAIAAAAAAAAAAAAA==","44;CgAAADQAXwA2ADYAMQABAAMAAQAAAAAAAAAKAAAANABfADYANgA0AAAAAAA=","58;AgAAADEAAQABAAoAAAA0AF8ANgA2ADYAAAAEAAMAAAAKAAAANABfADYANgA2AACAIAAAAAAAAAAAAA==","98;AgAAADEAAQABAAoAAAA0AF8ANgA2ADcAAAAcACcAAAAKAAAANABfADYANgA3AAoAAAA0AF8ANgA2ADUAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","34;CgAAADQAXwA2ADYANwABABwAAQAAAAAAAAAEAAAAAwAAAA==","87;AgAAADEAAQABAAoAAAA0AF8ANgA2ADUAAAADAAoAAAA0AF8ANgA2ADUAQgAAAAAAAAAAAAAACgAAADQAXwA2ADYANgABAAAACgAAADQAXwA2ADYANwAB","46;CgAAADQAXwA2ADYANQAeAAMAAAAAAEIAAAAAAAAAAAAAAEIAAAAAAAAAAAAAAA==","88;AgAAADEAAQABAAoAAAA0AF8ANgA2ADgAAAAcACcAAAAKAAAANABfADYANgA4AAAAAAAAgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==","46;CgAAADQAXwA2ADYAOAAdABwAAAAAAACAIAAAAAAAAAAAAACAIAAAAAAAAAAAAA==","34;CgAAADQAXwA2ADYAMwACABwAAQAAAAAAAAAEAAAAAAAAAA==","98;AgAAADEAAQABAAoAAAA0AF8ANgA2ADkAAAAcACcAAAAKAAAANABfADYANgA5AAoAAAA0AF8ANgA2ADEAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","46;CgAAADQAXwA2ADYAOQAdABwAAAAAAACAIAAAAAAAAAAAAACAIAAAAAAAAAAAAA==","44;CgAAADQAXwA2ADUAMwABAAMAAQAAAAAAAAAKAAAANABfADYANgA5AAAAAAA=","98;AgAAADEAAQABAAoAAAA0AF8ANgA3ADAAAAAcACcAAAAKAAAANABfADYANwAwAAoAAAA0AF8ANgA2ADEAAIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","46;CgAAADQAXwA2ADcAMAAdABwAAAAAAACAIAAAAAAAAAAAAACAIAAAAAAAAAAAAA==","44;CgAAADQAXwA2ADUAMwABAAMAAQAAAAEAAAAKAAAANABfADYANwAwAAAAAAA=","62;CgAAADQAXwA2ADYAMQACAAMAAgAAAAAAAAAKAAAANABfADYANgA0AAAAAAAKAAAANABfADYANgAzAAAAAAA=","36;AgAAADIAAQACAAEAAAAAAAAACgAAADQAXwA2ADUANwAAAAAA"]'
  await ooClient.makeChanges({ changes })
  ooClient.disconnect()
  sleep(1)
}

export default open_change_save_010
